name: Bump formulae and casks on schedule or request

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # Every Thursday 12 am
    - cron: "0 12 * * 4"

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump-formulae:
    if: github.repository == 'HuaDeity/homebrew-tap'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/brew:main
    env:
      GNUPGHOME: /tmp/gnupghome
      HOMEBREW_DEVELOPER: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Bump formulae
        id: autobump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMULAE: ${{ inputs.formulae }}
        continue-on-error: true
        run: |
          BREW_BUMP=(brew bump --no-fork --open-pr --formulae --bump-synced)
          if [[ -n "${FORMULAE-}" ]]; then
            xargs -t "${BREW_BUMP[@]}" <<<"${FORMULAE}"
          else
            "${BREW_BUMP[@]}" --tap=HuaDeity/tap
          fi

  autobump-casks:
    if: github.repository == 'HuaDeity/homebrew-tap'
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Bump casks
        id: autobump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CASKS: ${{ inputs.casks }}
        continue-on-error: true
        run: |
          BREW_BUMP=(brew bump --no-fork --open-pr --casks)
          if [[ -n "${CASKS-}" ]]; then
            xargs "${BREW_BUMP[@]}" <<<"${CASKS}"
          else
            "${BREW_BUMP[@]}" --tap=huadeity/tap
          fi
