name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  tap_syntax:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/brew:main
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          core: true

      - run: brew test-bot --only-tap-syntax

  test-bot:
    if: github.event_name == 'pull_request'
    needs: tap_syntax
    strategy:
      matrix:
        include:
          - runner: macos-latest
          - runner: ubuntu-latest
            container: ghcr.io/homebrew/brew:main
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container || '' }}
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOTTLES_DIR: ${{ github.workspace }}/bottles
    steps:
      - name: Pre-test steps
        uses: Homebrew/actions/pre-build@main
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}

      - name: Test formulae
        run: brew test-bot --only-formulae --only-json-tab
        working-directory: ${{ env.BOTTLES_DIR }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post-build steps
        if: always()
        uses: Homebrew/actions/post-build@main
        with:
          runner: ${{ matrix.runner }}
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ env.BOTTLES_DIR }}/logs
